controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

catalog:
    path: /
    controller: App\Controller\CatalogController::index