controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

main:
    path: /
    controller: App\Controller\ProductController::getProducts
    methods: ['GET']

getProducts:
    path: /catalog/products
    controller: App\Controller\ProductController::getProducts
    methods: ['GET']

showProduct:
    path: /catalog/product/{id}
    controller: App\Controller\ProductController::getSingleProduct
    methods: ['GET']

createProduct:
    path: /catalog/createProduct
    controller: App\Controller\ProductController::createProduct
    methods: ['GET', 'POST']

updateProduct:
    path: /catalog/updateProduct/{id}
    controller: App\Controller\ProductController::updateProduct

deleteProduct:
    path: /catalog/deleteProduct/{id}
    controller: App\Controller\ProductController::deleteProduct
    methods: ['GET', 'DELETE']